"""empty message

Revision ID: 1c2c9bfcb76e
Revises: d07666fa23f5
Create Date: 2019-04-20 00:39:03.443032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2c9bfcb76e'
down_revision = 'd07666fa23f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.drop_table(' categorias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' categorias',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'" categorias_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=' categorias_pkey'),
    sa.UniqueConstraint('nome', name=' categorias_nome_key')
    )
    op.drop_table('categorias')
    # ### end Alembic commands ###
