"""empty message

Revision ID: 1d660c8f7c59
Revises: 8f9bb7fa9857
Create Date: 2019-04-20 00:21:57.022324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d660c8f7c59'
down_revision = '8f9bb7fa9857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(' categorias', sa.Column('nome', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(' categorias', 'nome')
    # ### end Alembic commands ###
