"""empty message

Revision ID: 1fe570528255
Revises: 88f55545ba5b
Create Date: 2019-05-29 11:52:51.306760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe570528255'
down_revision = '88f55545ba5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'funcionarios', ['login'])
    op.add_column('produtos', sa.Column('url', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'produtos', ['url'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'produtos', type_='unique')
    op.drop_column('produtos', 'url')
    op.drop_constraint(None, 'funcionarios', type_='unique')
    # ### end Alembic commands ###
