"""empty message

Revision ID: 777de803c858
Revises: 2d67a4986795
Create Date: 2019-06-08 23:22:04.359202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '777de803c858'
down_revision = '2d67a4986795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('valor_unidade', sa.Float(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens')
    # ### end Alembic commands ###
