"""empty message

Revision ID: 8f9bb7fa9857
Revises: e93bc2d900ab
Create Date: 2019-04-20 00:13:57.953922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f9bb7fa9857'
down_revision = 'e93bc2d900ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(' categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(' categorias')
    # ### end Alembic commands ###
