"""empty message

Revision ID: e93bc2d900ab
Revises: 5649bf6d0e87
Create Date: 2019-04-20 00:04:06.466091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93bc2d900ab'
down_revision = '5649bf6d0e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'clientes', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientes', type_='unique')
    # ### end Alembic commands ###
